# Use this file for development purposes with hot reloading

version: "3.8"

services:
  # The database is the same as production,
  # but we use the dev file to start it with the others.
  postgres-db:
    build: ./database
    container_name: postgres-db-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Development Backend ---
  # This is completely different from the production one .

  #NOTE:
  #START :
  #   docker-compose -f docker-compose.dev.yml up --build
  #STOP :
  #   docker-compose -f docker-compose.dev.yml down

  backend:
    container_name: express-backend-dev
    # 1. We use the node image directly, NOT the Dockerfile
    image: node:22-alpine3.22
    working_dir: /app
    # 2. We run the 'dev' command to start nodemon
    command: sh -c "yarn install && yarn dev"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}
      - DB_HOST=postgres-db # Connects to the DB service above
      - DB_PORT=5432
      - DB_NAME=${DB}
      - API_PORT=${API_PORT}
    ports:
      - "8080:8080"
    # 3. We use VOLUMES to sync our code live
    volumes:
      # This maps your local folder into the container
      - ./backend:/app
      # This keeps the container's node_modules separate
      - /app/node_modules
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data: {}
