version: "3.8"

services:
  pgdb:
    build:
      context: ./database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/postgresql/data

  ingestor:
    container_name: ingestor
    image: node:alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PORT=8080
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./ingestor:/app
      - /app/node_modules

volumes:
  postgres:
    driver: local
